### ISSUE TITLE
Too much warnings of 'duplicate definition'

### ISSUE THREAD

**Issue by k06a** [zemse/hardhat-tracer#23]
I know there is issue with some errors defined in multiple contracts, but can we not see this warnings before each trace line?

<img width="675" alt="image" src="https://user-images.githubusercontent.com/702124/212331269-7a347fb9-82a4-4301-a967-94b2f0490db7.png">

**Comment by zemse** [comment]
This was fixed on the [v2-beta](https://github.com/zemse/hardhat-tracer/tree/v2-beta) branch. You can try it using `npm i hardhat-tracer@beta`. I'll fix this on the v1 branch soon.

**Comment by k06a** [comment]
Thanks!
