### ISSUE TITLE
Upgrade PeerDependencies Version for Hardhat

### ISSUE THREAD

**Issue by Confucian-e** [zemse/hardhat-tracer#67]
Hardhat now has released the version 2.22. But `peerDependencies` are still `>=2.16 <2.21.0`, please support new version.

**Comment by zemse** [comment]
Hardhat 2.21 and introduces EDR and this plugin currently does not work with it out of the box yet hence the peer dependency constraint was recently added. 

Regarding upgrading this plugin to support EDR, is an issue regarding it https://github.com/NomicFoundation/edr/issues/299. For reference, here is a WIP branch however it still missing features and is not ready to be published at this stage https://github.com/zemse/hardhat-tracer/tree/v3

I am trying to support EDR asap.

**Comment by Confucian-e** [comment]
Thank you sir. The trace plugin you developed has tremendous significance for contract developers.

**Comment by Confucian-e** [comment]
I reopen this issue to wait for v3 publish.
When support hardhat EDR, you could close this.

**Comment by zemse** [comment]
Just published `hardhat-tracer@3.0.1` based on the hardhat EDR. Note that this needs [hardhat >= 2.22.5](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.22.5).

**Comment by Confucian-e** [comment]
I have tried and it works smoothly, so I close this issue. Thank you for your work!
