### ISSUE TITLE
Enable tracing for interactive testing on fork with hardhat console

### ISSUE THREAD

**Issue by Unstoppable-DeFi** [zemse/hardhat-tracer#68]
Is it not possible to have tracing for a transaction sent on local hardhat network (forked) interactively through the hardhat console?

**Comment by zemse** [comment]
Does `npx hardhat node --trace` work in this case?

**Comment by Unstoppable-DeFi** [comment]
> Does `npx hardhat node --trace` work in this case?

I couldn't make it work..

**Comment by zemse** [comment]
What error/behavior do you get? What hardhat version are you using?

**Comment by zemse** [comment]
This issue was just fixed in v2.8.2 of this plugin.

**Comment by Unstoppable-DeFi** [comment]
Works great now, thanks!
