### ISSUE TITLE
No logs on a reverted transaction

### ISSUE THREAD

**Issue by snapple42** [zemse/hardhat-tracer#7]
I have a small contract, and when a transaction is reverted, there are no logs displayed..   
  
I run the contract with a good, non-reverted function call, and all the logs are displayed.  
  
since, I can't upload a "sol" file:  
contracts/test.sol  
```
// SPDX-License-Identifier: None
pragma solidity >=0.8.7;


contract test {
    event Received(address sender, uint amount);

    function good() public payable returns (uint) {
        emit Received(msg.sender, msg.value);
        return msg.value;
    }

    function bad() public payable returns (uint) {
        emit Received(msg.sender, msg.value);
        revert("Bad call");        
    }
}
```
  
And the test script:  
test/test.js  
```
const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("Test", function () {
    it("Should perform tests", async function () {
        const Test = await ethers.getContractFactory("test");
        const test = await Test.deploy();
        expect(await test.deployed(),"Not deployed");
        console.log("GOOD CALL");
        await test.good({value: "10000000000000000000"});
        console.log("BAD CALL");
        await test.bad({value: "10000000000000000000"});
  });
});
```
  
run with:  
```
npx hardhat test --logs
```

Relavant output expecting "[Receiver] Received(from=[Sender], amount=10000000000000000000)" in both calls:  
```
  Test
GOOD CALL
[Receiver] Received(from=[Sender], amount=10000000000000000000)
BAD CALL
    1) Should perform tests


  0 passing (3s)
  1 failing

  1) Test
       Should perform tests:
     Error: VM Exception while processing transaction: reverted with reason string 'Bad call'
```

**Comment by zemse** [comment]
Just rewrote the plugin over the weekend. And now logs should be displayed in reverted transactions as well. If you can, please try [v1.1.0-rc.1](https://github.com/zemse/hardhat-tracer/releases/tag/v1.1.0-rc.1) if it works for you.

**Comment by zemse** [comment]
I believe this has been fixed. You can also try the latest v2, which prints the view function calls and to only see reverted calls or txs, `--traceError` can be used.
