### ISSUE TITLE
"Hardhat Tracer wanted to print trace, but lastTrace is undefined." when using `--trace-error`

### ISSUE THREAD

**Issue by fvictorio** [zemse/hardhat-tracer#72]
Versions used:
- Hardhat 2.22.6
- hardhat-tracer: 3.0.2

### Reproduction steps

Solidity file:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Foo {
    uint public x;

    function incBy(uint by) public {
        require(by > 0, "by must be positive");
        x += by;
    }
}
```

Test file:

```javascript
const { expect } = require("chai");

describe("Foo", function () {
  it("test", async function () {
    const foo = await ethers.deployContract("Foo")

    await expect(foo.incBy(0)).to.be.reverted;
  });
});
```

Hardhat config:

```javascript
require("@nomicfoundation/hardhat-toolbox");
require("hardhat-tracer");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.24",
};
```

Run `npx hardhat test --trace-error`. Curiously, `--trace` seems to work fine.

**Comment by zemse** [comment]
Thanks for reporting, I just pushed a [commit](https://github.com/zemse/hardhat-tracer/commit/7d3e4d2713c9126e6da06880f672151b1f74ff60) and released 3.0.3. Does that fix this issue?

**Comment by shark0der** [comment]
I can confirm it fixed the issue. Thank you!

**Comment by fvictorio** [comment]
@shark0der was the one that pointed me to this problem, so I'm going to assume it's fixed. Thanks for the quick fix, @zemse!
